import type { Dish } from "./types";

export const DISHES: Dish[] = [
  // ——— Завтраки ———
  {
    id: "oatmeal-berries",
    name: "Овсянка с ягодами и мёдом",
    mealType: "breakfast",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "овсяные хлопья", amount: "400 г", category: "grains" },
      { name: "молоко", amount: "1 л", category: "dairy" },
      { name: "ягоды", amount: "300 г", category: "frozen" },
      { name: "мёд", amount: "3 ст. л.", category: "other" },
    ],
    tags: ["крупы", "быстро", "овощи"],
    difficulty: "easy",
    batchCooking: false,
    cuisine: ["home", "any"],
  },
  {
    id: "syrniki",
    name: "Сырники",
    mealType: "breakfast",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "творог", amount: "500 г", category: "dairy" },
      { name: "яйца", amount: "2 шт.", category: "dairy" },
      { name: "мука", amount: "4 ст. л.", category: "grains" },
      { name: "сахар", amount: "2 ст. л.", category: "other" },
      { name: "сметана", amount: "200 г", category: "dairy" },
    ],
    tags: ["творог", "яйца", "быстро"],
    difficulty: "easy",
    batchCooking: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "blini",
    name: "Блины",
    mealType: "breakfast",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "мука", amount: "300 г", category: "grains" },
      { name: "молоко", amount: "500 мл", category: "dairy" },
      { name: "яйца", amount: "2 шт.", category: "dairy" },
      { name: "сметана", amount: "200 г", category: "dairy" },
      { name: "сгущёнка", amount: "1 банка", category: "dairy" },
    ],
    tags: ["яйца", "быстро"],
    difficulty: "medium",
    batchCooking: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "oladi",
    name: "Оладьи",
    mealType: "breakfast",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "кефир", amount: "500 мл", category: "dairy" },
      { name: "мука", amount: "300 г", category: "grains" },
      { name: "яйца", amount: "1 шт.", category: "dairy" },
      { name: "сметана", amount: "150 г", category: "dairy" },
    ],
    tags: ["яйца", "быстро"],
    difficulty: "easy",
    batchCooking: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "omelette-veg",
    name: "Омлет с овощами",
    mealType: "breakfast",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "яйца", amount: "6 шт.", category: "dairy" },
      { name: "молоко", amount: "100 мл", category: "dairy" },
      { name: "помидоры", amount: "2 шт.", category: "vegetables" },
      { name: "перец болгарский", amount: "1 шт.", category: "vegetables" },
      { name: "зелень", amount: "пучок", category: "vegetables" },
    ],
    tags: ["яйца", "овощи", "быстро"],
    difficulty: "easy",
    batchCooking: false,
    cuisine: ["home", "european", "any"],
  },
  {
    id: "cottage-cheese-berries",
    name: "Творог со сметаной и ягодами",
    mealType: "breakfast",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "творог", amount: "600 г", category: "dairy" },
      { name: "сметана", amount: "150 г", category: "dairy" },
      { name: "ягоды", amount: "250 г", category: "frozen" },
      { name: "мёд", amount: "2 ст. л.", category: "other" },
    ],
    tags: ["творог", "быстро"],
    difficulty: "easy",
    batchCooking: false,
    cuisine: ["home", "kids", "any"],
  },
  {
    id: "eggs-toast",
    name: "Яйца с тостами",
    mealType: "breakfast",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "яйца", amount: "4 шт.", category: "dairy" },
      { name: "хлеб", amount: "8 ломтиков", category: "grains" },
      { name: "масло сливочное", amount: "30 г", category: "dairy" },
    ],
    tags: ["яйца", "быстро"],
    difficulty: "easy",
    batchCooking: false,
    cuisine: ["european", "home", "any"],
  },
  {
    id: "cottage-casserole",
    name: "Творожная запеканка",
    mealType: "breakfast",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "творог", amount: "500 г", category: "dairy" },
      { name: "яйца", amount: "2 шт.", category: "dairy" },
      { name: "манка", amount: "3 ст. л.", category: "grains" },
      { name: "сметана", amount: "100 г", category: "dairy" },
      { name: "изюм", amount: "50 г", category: "other" },
    ],
    tags: ["творог", "яйца", "запеканка"],
    difficulty: "medium",
    batchCooking: true,
    cuisine: ["russian", "home", "any"],
  },

  // ——— Обеды ———
  {
    id: "chicken-noodle-soup",
    name: "Куриный суп с лапшой",
    mealType: "lunch",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "куриное филе", amount: "400 г", category: "meat" },
      { name: "лапша", amount: "200 г", category: "grains" },
      { name: "морковь", amount: "2 шт.", category: "vegetables" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
      { name: "картофель", amount: "3 шт.", category: "vegetables" },
    ],
    tags: ["мясо", "крупы", "овощи"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["home", "russian", "any"],
  },
  {
    id: "borscht-simple",
    name: "Упрощённый борщ",
    mealType: "lunch",
    forChildren: false,
    forAdults: true,
    budget: "medium",
    ingredients: [
      { name: "говядина", amount: "400 г", category: "meat" },
      { name: "свёкла", amount: "2 шт.", category: "vegetables" },
      { name: "капуста", amount: "300 г", category: "vegetables" },
      { name: "картофель", amount: "3 шт.", category: "vegetables" },
      { name: "морковь", amount: "1 шт.", category: "vegetables" },
      { name: "сметана", amount: "150 г", category: "dairy" },
    ],
    tags: ["мясо", "овощи"],
    difficulty: "hard",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["russian", "any"],
  },
  {
    id: "buckwheat-chicken-lunch",
    name: "Гречка с курицей",
    mealType: "lunch",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "гречка", amount: "300 г", category: "grains" },
      { name: "куриное филе", amount: "500 г", category: "meat" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
    ],
    tags: ["мясо", "крупы"],
    difficulty: "easy",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["home", "russian", "any"],
  },
  {
    id: "tuna-salad",
    name: "Салат с тунцом и яйцом",
    mealType: "lunch",
    forChildren: false,
    forAdults: true,
    budget: "medium",
    ingredients: [
      { name: "тунец консервированный", amount: "2 банки", category: "meat" },
      { name: "яйца", amount: "3 шт.", category: "dairy" },
      { name: "огурцы", amount: "2 шт.", category: "vegetables" },
      { name: "помидоры", amount: "2 шт.", category: "vegetables" },
      { name: "майонез", amount: "3 ст. л.", category: "other" },
    ],
    tags: ["рыба", "яйца", "овощи", "быстро", "можно взять на работу"],
    difficulty: "easy",
    batchCooking: false,
    takeawayFriendly: true,
    cuisine: ["european", "any"],
  },
  {
    id: "chicken-pilaf",
    name: "Плов с курицей",
    mealType: "lunch",
    forChildren: true,
    forAdults: true,
    budget: "medium",
    ingredients: [
      { name: "куриное филе", amount: "500 г", category: "meat" },
      { name: "рис", amount: "400 г", category: "grains" },
      { name: "морковь", amount: "2 шт.", category: "vegetables" },
      { name: "лук", amount: "2 шт.", category: "vegetables" },
    ],
    tags: ["мясо", "крупы", "овощи"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["home", "any"],
  },
  {
    id: "mashed-potato-cutlets",
    name: "Картофельное пюре с котлетами",
    mealType: "lunch",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "картофель", amount: "1 кг", category: "vegetables" },
      { name: "фарш", amount: "500 г", category: "meat" },
      { name: "молоко", amount: "200 мл", category: "dairy" },
      { name: "яйца", amount: "1 шт.", category: "dairy" },
    ],
    tags: ["мясо", "овощи"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "veg-soup",
    name: "Овощной суп",
    mealType: "lunch",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "картофель", amount: "4 шт.", category: "vegetables" },
      { name: "морковь", amount: "2 шт.", category: "vegetables" },
      { name: "кабачок", amount: "1 шт.", category: "vegetables" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
      { name: "вермишель", amount: "100 г", category: "grains" },
    ],
    tags: ["овощи", "крупы"],
    difficulty: "easy",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["home", "kids", "any"],
  },
  {
    id: "pasta-cheese",
    name: "Макароны с сыром",
    mealType: "lunch",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "макароны", amount: "400 г", category: "grains" },
      { name: "сыр", amount: "200 г", category: "dairy" },
      { name: "молоко", amount: "200 мл", category: "dairy" },
      { name: "масло сливочное", amount: "30 г", category: "dairy" },
    ],
    tags: ["крупы", "быстро"],
    difficulty: "easy",
    batchCooking: false,
    cuisine: ["kids", "home", "any"],
  },

  // ——— Ужины ———
  {
    id: "lazy-lasagna",
    name: "Ленивая лазанья",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "medium",
    ingredients: [
      { name: "фарш", amount: "600 г", category: "meat" },
      { name: "макароны", amount: "300 г", category: "grains" },
      { name: "томатная паста", amount: "3 ст. л.", category: "other" },
      { name: "сыр", amount: "200 г", category: "dairy" },
      { name: "сметана", amount: "200 г", category: "dairy" },
    ],
    tags: ["мясо", "крупы", "запеканка"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["european", "home", "any"],
  },
  {
    id: "chicken-mushroom-julienne",
    name: "Жульен с курицей и грибами",
    mealType: "dinner",
    forChildren: false,
    forAdults: true,
    budget: "medium",
    ingredients: [
      { name: "куриное филе", amount: "500 г", category: "meat" },
      { name: "шампиньоны", amount: "300 г", category: "vegetables" },
      { name: "сметана", amount: "250 г", category: "dairy" },
      { name: "сыр", amount: "150 г", category: "dairy" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
    ],
    tags: ["мясо", "овощи"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["russian", "european", "any"],
  },
  {
    id: "pelmeni-salad",
    name: "Пельмени с овощным салатом",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "пельмени", amount: "800 г", category: "frozen" },
      { name: "огурцы", amount: "2 шт.", category: "vegetables" },
      { name: "помидоры", amount: "2 шт.", category: "vegetables" },
      { name: "сметана", amount: "150 г", category: "dairy" },
    ],
    tags: ["мясо", "овощи", "быстро"],
    difficulty: "easy",
    batchCooking: false,
    cuisine: ["russian", "kids", "any"],
  },
  {
    id: "fish-sticks-rice",
    name: "Рыбные палочки с рисом",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "рыбные палочки", amount: "500 г", category: "frozen" },
      { name: "рис", amount: "300 г", category: "grains" },
      { name: "овощи замороженные", amount: "300 г", category: "frozen" },
    ],
    tags: ["рыба", "крупы", "быстро"],
    difficulty: "easy",
    batchCooking: false,
    cuisine: ["kids", "home", "any"],
  },
  {
    id: "nuggets-mash",
    name: "Наггетсы с картофельным пюре",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "наггетсы", amount: "500 г", category: "frozen" },
      { name: "картофель", amount: "800 г", category: "vegetables" },
      { name: "молоко", amount: "150 мл", category: "dairy" },
      { name: "кетчуп", amount: "по вкусу", category: "other" },
    ],
    tags: ["мясо", "овощи", "быстро"],
    difficulty: "easy",
    batchCooking: false,
    cuisine: ["kids", "any"],
  },
  {
    id: "chicken-cutlets-buckwheat",
    name: "Куриные котлеты с гречкой",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "куриный фарш", amount: "600 г", category: "meat" },
      { name: "гречка", amount: "350 г", category: "grains" },
      { name: "яйца", amount: "1 шт.", category: "dairy" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
    ],
    tags: ["мясо", "крупы", "яйца"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "pasta-mince",
    name: "Макароны с фаршем",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "макароны", amount: "400 г", category: "grains" },
      { name: "фарш", amount: "500 г", category: "meat" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
      { name: "томатная паста", amount: "2 ст. л.", category: "other" },
    ],
    tags: ["мясо", "крупы"],
    difficulty: "easy",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["home", "any"],
  },
  {
    id: "chicken-veg-stew",
    name: "Овощное рагу с курицей",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "куриное филе", amount: "500 г", category: "meat" },
      { name: "кабачок", amount: "1 шт.", category: "vegetables" },
      { name: "морковь", amount: "2 шт.", category: "vegetables" },
      { name: "перец болгарский", amount: "2 шт.", category: "vegetables" },
      { name: "рис", amount: "200 г", category: "grains" },
    ],
    tags: ["мясо", "овощи", "крупы"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["home", "any"],
  },
  {
    id: "potato-casserole",
    name: "Картофельная запеканка",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "картофель", amount: "1 кг", category: "vegetables" },
      { name: "фарш", amount: "400 г", category: "meat" },
      { name: "сыр", amount: "150 г", category: "dairy" },
      { name: "яйца", amount: "2 шт.", category: "dairy" },
      { name: "сметана", amount: "200 г", category: "dairy" },
    ],
    tags: ["мясо", "овощи", "запеканка", "яйца"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "rice-chicken-veg",
    name: "Рис с курицей и овощами",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "рис", amount: "350 г", category: "grains" },
      { name: "куриное филе", amount: "500 г", category: "meat" },
      { name: "морковь", amount: "1 шт.", category: "vegetables" },
      { name: "горошек замороженный", amount: "150 г", category: "frozen" },
    ],
    tags: ["мясо", "крупы", "овощи"],
    difficulty: "easy",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["home", "any"],
  },
  {
    id: "meatball-soup",
    name: "Суп с фрикадельками",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "фарш", amount: "400 г", category: "meat" },
      { name: "картофель", amount: "4 шт.", category: "vegetables" },
      { name: "морковь", amount: "1 шт.", category: "vegetables" },
      { name: "вермишель", amount: "100 г", category: "grains" },
    ],
    tags: ["мясо", "овощи", "крупы"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "buckwheat-meat-sauce",
    name: "Гречка с мясной подливкой",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "гречка", amount: "350 г", category: "grains" },
      { name: "фарш", amount: "500 г", category: "meat" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
      { name: "морковь", amount: "1 шт.", category: "vegetables" },
    ],
    tags: ["мясо", "крупы"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "baked-fish-veg",
    name: "Запечённая рыба с овощами",
    mealType: "dinner",
    forChildren: false,
    forAdults: true,
    budget: "medium",
    ingredients: [
      { name: "филе белой рыбы", amount: "600 г", category: "meat" },
      { name: "лимон", amount: "1 шт.", category: "vegetables" },
      { name: "кабачок", amount: "1 шт.", category: "vegetables" },
      { name: "помидоры", amount: "2 шт.", category: "vegetables" },
    ],
    tags: ["рыба", "овощи"],
    difficulty: "medium",
    batchCooking: false,
    cuisine: ["european", "any"],
  },
  {
    id: "meatballs-tomato",
    name: "Тефтели в томатном соусе",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "фарш", amount: "600 г", category: "meat" },
      { name: "рис", amount: "100 г", category: "grains" },
      { name: "томатная паста", amount: "3 ст. л.", category: "other" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
      { name: "сметана", amount: "100 г", category: "dairy" },
    ],
    tags: ["мясо", "крупы"],
    difficulty: "medium",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["russian", "home", "any"],
  },
  {
    id: "chicken-pan-veg",
    name: "Куриная грудка с овощами на сковороде",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "medium",
    ingredients: [
      { name: "куриное филе", amount: "600 г", category: "meat" },
      { name: "брокколи", amount: "300 г", category: "vegetables" },
      { name: "морковь", amount: "2 шт.", category: "vegetables" },
      { name: "оливковое масло", amount: "2 ст. л.", category: "other" },
    ],
    tags: ["мясо", "овощи", "быстро"],
    difficulty: "easy",
    batchCooking: false,
    takeawayFriendly: true,
    cuisine: ["european", "home", "any"],
  },
  {
    id: "bean-veg-stew",
    name: "Рагу из фасоли с овощами",
    mealType: "dinner",
    forChildren: true,
    forAdults: true,
    budget: "low",
    ingredients: [
      { name: "фасоль консервированная", amount: "2 банки", category: "other" },
      { name: "морковь", amount: "2 шт.", category: "vegetables" },
      { name: "лук", amount: "1 шт.", category: "vegetables" },
      { name: "томатная паста", amount: "2 ст. л.", category: "other" },
    ],
    tags: ["овощи"],
    difficulty: "easy",
    batchCooking: true,
    takeawayFriendly: true,
    cuisine: ["home", "european", "any"],
  },
];
